Documentation for `Scheduler.java`
planit-gcal/planit pull request #22
Opened 2022-10-17 06:39 UTC by sereczeq

2022-10-17 06:46 UTC, Kaspr-whtev approved these changes

2022-10-19 13:48 UTC, Kartm requested changes

2022-10-19 13:48 UTC, Kartm commented on backend/src/main/java/planit/people/preparation/Scheduling/Scheduler.java
> +     * Filteres the given intervals so that only the intervals between start and end are returned. If any interval goes beyond boundaries, it will be cut.
typo in `Filteres`

2022-10-19 14:06 UTC, Kartm approved these changes

2022-10-19 14:06 UTC, merged