`FreeTimeFinder` - algorithm to find a date that suits all required users and most non required
planit-gcal/planit pull request #60
Opened 2022-11-29 14:50 UTC by sereczeq

Don't check the other files yet. They're done by Mustafa. **Please only check `FreeTimeFinder`**

2022-11-30 16:31 UTC, Kaspr-whtev requested changes

2022-12-07 14:37 UTC, sereczeq reviewed
I'd change some things, but overall good. Love the documentation

2022-12-07 14:37 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/GoogleConnector/GoogleHelper.java
> +        Map<String, Map<Long, List<Interval>>> freeIntervalsForAllUsers = getFreeIntervalForAll(freeBusyIntervalsForAllUsers, newEventDetail.start_date(), newEventDetail.end_date(), durationInMinutes
Make a class or a struct to hold this data

2022-12-07 14:37 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/GoogleConnector/GoogleHelper.java
> +        assert startTime != null;
[Assertions should never be triggered in production code, and are indicative of a bug or misuse of a code path](https://stackoverflow.com/questions/2758224/what-does-the-java-assert-keyword-do-and-when-should-it-be-used)

2022-12-07 14:37 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/GoogleConnector/GoogleHelper.java
> +        Map<String, Map<Long, List<CompletableFuture<List<Interval>>>>> futureCallsMap = new HashMap<>();
This is unreadable

2022-12-07 14:37 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/GoogleConnector/GoogleHelper.java
> +                    futureCalls.add(futureCall);
Why do you keep `size` variable. As far as I understand each time `size` is incremented you also add elements to `futureCalls` and `futureIntervalForAUser` so size can be infered from that

2022-12-07 14:37 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/GoogleConnector/GoogleHelper.java
> +                futureCalls.add(futureCall);
similar as above, size seems redundant here

2022-12-07 14:37 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/GoogleConnector/GoogleHelper.java
> +                result.get(key).put(id, freeIntervalsForAllUsers.get(key).get(id).get());
bleeeh

2022-12-07 14:39 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/Scheduling/Converter.java
> +                if (key.equals("required")) {
Don't hardcode strings in the middle of the code

2022-12-07 14:42 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/Scheduling/Scheduler.java
> +            filtered.addAll(splitInterval(interval, duration));
I think just `filtered.add()` would work here, no need for `addAll()`

2022-12-07 14:54 UTC, sereczeq reviewed
This cannot be merged! Changes break the functionality of the code

2022-12-07 14:54 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/Scheduling/Scheduler.java
> +            if (interval.toDuration().compareTo(duration) >= 0) {
`while true` but first line is an if check. Put that condition inside while

2022-12-07 14:54 UTC, sereczeq commented on backend/src/main/java/planit/people/preparation/Scheduling/Scheduler.java
> +            filtered.addAll(splitInterval(interval, duration));
This <b> functionality is wrong </b> This method is supposed to filter out intervals shorter than duration, not cut them. Slicing the intervals will create a lot of false negatives while searching for the time slots

2022-12-07 14:55 UTC, Kartm requested changes

2022-12-09 09:56 UTC, Kartm approved these changes

2022-12-09 09:56 UTC, merged